// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBts0nqfRRj0cTVCzgmj6BiyEexzbF8Vvw',
    appId: '1:141255105848:web:f774cf94310236c68135cd',
    messagingSenderId: '141255105848',
    projectId: 'clubx-365d0',
    authDomain: 'clubx-365d0.firebaseapp.com',
    storageBucket: 'clubx-365d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFasG_cX8ODPznBC_9wsX9acRVahZ0Fw',
    appId: '1:141255105848:android:93f53971bc13cc368135cd',
    messagingSenderId: '141255105848',
    projectId: 'clubx-365d0',
    storageBucket: 'clubx-365d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi6xhxUJviACXwJWsv3g4PwWmmZpU9LiE',
    appId: '1:141255105848:ios:fc3e53b10a96abf98135cd',
    messagingSenderId: '141255105848',
    projectId: 'clubx-365d0',
    storageBucket: 'clubx-365d0.firebasestorage.app',
    iosBundleId: 'com.example.clubx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi6xhxUJviACXwJWsv3g4PwWmmZpU9LiE',
    appId: '1:141255105848:ios:fc3e53b10a96abf98135cd',
    messagingSenderId: '141255105848',
    projectId: 'clubx-365d0',
    storageBucket: 'clubx-365d0.firebasestorage.app',
    iosBundleId: 'com.example.clubx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBts0nqfRRj0cTVCzgmj6BiyEexzbF8Vvw',
    appId: '1:141255105848:web:0aafb571885bc0418135cd',
    messagingSenderId: '141255105848',
    projectId: 'clubx-365d0',
    authDomain: 'clubx-365d0.firebaseapp.com',
    storageBucket: 'clubx-365d0.firebasestorage.app',
  );

}